name: deploy-app-website
concurrency: azure-app-deploy

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  AZURE_CONTAINER_REGISTRY_NAME: photoragacr
  AZURE_RESOURCEGROUP_NAME: photorag
  AZURE_WEB_APP_NAME: photoragweb
  NEXT_PUBLIC_SITE_URL: https://rag.photomuse.ai

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy Bicep
        uses: azure/arm-deploy@v2
        with:
          deploymentName: ${{ github.run_number }}
          resourceGroupName: ${{ env.AZURE_RESOURCEGROUP_NAME }}
          template: ./deploy/main.bicep
          parameters: >
            acrName=${{ env.AZURE_CONTAINER_REGISTRY_NAME }}
            dbUrl=${{ secrets.DB_URL }}
            emailConnString=${{ secrets.AZURE_EMAIL_CONN_STRING }}
            siteUrl=${{ env.NEXT_PUBLIC_SITE_URL }}
            webAppName=${{ env.AZURE_WEB_APP_NAME }}
          scope: 'resourcegroup'

      - name: Build and push image to ACR
        run: |
          az acr build --resource-group ${{ env.AZURE_RESOURCEGROUP_NAME }} \
                       --registry ${{ env.AZURE_CONTAINER_REGISTRY_NAME }} \
                       --image ${{ env.AZURE_WEB_APP_NAME }}:${{ github.sha }} \
                       --image ${{ env.AZURE_WEB_APP_NAME }}:latest .

      - name: Update Web App with new image
        run: |
          az webapp config container set --name ${{ env.AZURE_WEB_APP_NAME }} \
                                        --resource-group ${{ env.AZURE_RESOURCEGROUP_NAME }} \
                                        --container-image-name ${{ env.AZURE_CONTAINER_REGISTRY_NAME }}.azurecr.io/${{ env.AZURE_WEB_APP_NAME }}:${{ github.sha }}

      - name: Restart Web App
        run: |
          az webapp restart --name ${{ env.AZURE_WEB_APP_NAME }} \
                            --resource-group ${{ env.AZURE_RESOURCEGROUP_NAME }}
